//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BracketAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleTeam
    {
        public int Team_ID { get; set; }
        public int People_ID { get; set; }
        public string Role { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Team Team { get; set; }
    }
}
