//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BracketAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.TournamentsTeams = new HashSet<TournamentsTeam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sport { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public int Organizer_ID { get; set; }
        public string Location { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentsTeam> TournamentsTeams { get; set; }
    }
}
